Repository apache/iggy, pull requests merged in 2025-01, with the labels that each got.

#1392 ci: add labeller and labels script
  .github/labeler.yml
  .github/update-labels.sh
  .github/workflows/master-update-labels.yaml
  .github/workflows/pull-request-relabelling.yaml
  .github/workflows/sanity.yml
  .github/workflows/test_pr.yml
Labels: CI/CD

#1447 chore: order values in .dockerignore to test CI
  .dockerignore
Labels: maintenance

#1457 Add dependencies info
  dependencies.md
Labels: docs
